#include "graphics.h"
#include "gba.h"
#include "stdio.h"
// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
//#include "images/garbage.h"
#include "images/shaymin.h"
#include "images/flower.h"
#include "images/bee.h"


// TA-TODO: Add any draw/undraw functions for sub-elements of your app here.
// For example, for a snake game, you could have a drawSnake function
// or a drawFood function
//
// e.g.:
// static void drawSnake(Snake* snake);
// static void drawFood(Food* food);

// This function will be used to draw everything about the app
// including the background and whatnot.
void fullDrawAppState(AppState *state) {
    fillScreenDMA(0x1ee1);
    for (int i = 0; i < state->nflowers; i++){
        drawImageDMA(state->flowers[i].x, state->flowers[i].y, FLOWER_WIDTH, FLOWER_HEIGHT, flower);
    }
    for (int i = 0; i < state->nbees; i++){
        drawImageDMA(state->bees[i].x, state->bees[i].y, BEE_WIDTH, BEE_HEIGHT, bee);
    }
    drawImageDMA(state->shaymin.x, state->shaymin.y, SHAYMIN_WIDTH, SHAYMIN_HEIGHT, shaymin);
    char buffer[9]; //draw score string
    sprintf(buffer, "Score: %d", state->score);
    drawString(185, 3, buffer, BLACK); //columns is the first param THEN row
}


// This function will be used to undraw (i.e. erase) things that might
// move in a frame. E.g. in a Snake game, erase the Snake, the food & the score.
void undrawAppState(AppState *state) {
    drawRectDMA(state->shaymin.x, state->shaymin.y, SHAYMIN_WIDTH, SHAYMIN_HEIGHT, 0x1ee1);
    for (int i = 0; i < state->nflowers; i++) {
        if (!state->flowers[i].alive) { //if the flower is not alive, cover it
            drawRectDMA(state->flowers[i].x, state->flowers[i].y, FLOWER_WIDTH, FLOWER_HEIGHT, 0x1ee1);
        }
    }
    for (int i = 0; i < state->nbees; i++) {
        drawRectDMA(state->bees[i].x, state->bees[i].y, BEE_WIDTH, BEE_HEIGHT, 0x1ee1);
    }
    drawRectDMA(225, 0, 10, 10, 0x1ee1);
}

// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.
void drawAppState(AppState *state) {
    for (int i = 0; i < state->nbees; i++) {
        drawImageDMA(state->bees[i].x, state->bees[i].y, BEE_WIDTH, BEE_HEIGHT, bee);
    }
    drawImageDMA(state->shaymin.x, state->shaymin.y, SHAYMIN_WIDTH, SHAYMIN_HEIGHT, shaymin);
    char buffer[3];
    sprintf(buffer, "%d", state->score);
    drawString(227, 3, buffer, BLACK); //location of the integer portion (Ex."Score: " 7)
}
