#include "gba.h"
#include "logic.h"
#include "graphics.h"
// TA-TODO: Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
#include "images/startscreentext.h"
#include "images/control_adv.h"
#include "images/shaymin_superwin.h"
#include "images/winningscreen.h"
#include "images/losingscreen.h"

#include <stdio.h>
#include <stdlib.h>

// AppState enum definition
typedef enum {
    // TA-TODO: Add any additional states you need for your app.
    START,
    CONTROL,
    APP_INIT,
    APP,
    APP_WON_DRAW,
    APP_WON_NODRAW,
    APP_SUPER_WIN,
    APP_LOST_DRAW,
    APP_LOST_NODRAW
} GBAState;

int main(void) {
    // TA-TODO: Manipulate REG_DISPCNT here to set Mode 3.
    REG_DISPCNT = MODE3 | BG2_ENABLE;

    GBAState state = START;

    // We store the "previous" and "current" states.
    AppState currentAppState, nextAppState;

    // We store the current and previous values of the button input.
    u32 previousButtons = BUTTONS;
    u32 currentButtons = BUTTONS;

    while(1) {
        // Load the current state of the buttons
        waitForVBlank();
        currentButtons = BUTTONS;

        // TA-TODO: Manipulate the state machine below as needed.
        switch(state) {
            case START:
            // TA-TODO: Draw the start state here.
            drawFullScreenImageDMA(startscreentext);
            if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
                state = CONTROL;
            }
            break;
        case CONTROL:
            // TA-TODO: Check for a button press here to start the app.
            // Start the app by switching the state to APP_INIT.
            drawFullScreenImageDMA(control_adv);
            if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
                state = APP_INIT;
            }
            if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
                state = START;
            }
            break;
        case APP_INIT:
            // Initialize the app. Switch to the APP state.
            //waitForVBlank();
            initializeAppState(&currentAppState);

            // Draw the initial state of the app
            fullDrawAppState(&currentAppState);

            state = APP;
            break;
        case APP:
            // Process the app for one frame, store the next state
            nextAppState = processAppState(&currentAppState, currentButtons);

            // Wait for VBlank before we do any drawing.

            // Undraw the previous state
            undrawAppState(&currentAppState);

            // Draw the current state
            drawAppState(&nextAppState);

            // Now set the current state as the next state for the next iter.
            currentAppState = nextAppState;

            // Check if the app is exiting. If it is, then go to the exit state.
            if (currentAppState.gameWon) {
                state = APP_WON_DRAW;
            }
            if (currentAppState.gameSuperWin) {
                state = APP_SUPER_WIN;
            }
            if (currentAppState.gameLost) {
                state = APP_LOST_DRAW;
            }
            if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
                state = START;
            }
            break;
        case APP_WON_DRAW:
            // TA-TODO: Check for a button press here to go back to the start screen
            drawFullScreenImageDMA(winningscreen);
            state = APP_WON_NODRAW;
            break;
        case APP_WON_NODRAW:
            // TA-TODO: Check for a button press here to go back to the start screen
            if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
                state = START;
            }
            break;
        case APP_SUPER_WIN:
            drawFullScreenImageDMA(shaymin_superwin);
            if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
                state = START;
            }
            break;
        case APP_LOST_DRAW:
            // TA-TODO: Check for a button press here to go back to the start screen
            drawFullScreenImageDMA(losingscreen);
            state = APP_LOST_NODRAW;
            break;
        case APP_LOST_NODRAW:
            // TA-TODO: Check for a button press here to go back to the start screen
            if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
                state = START;
            }
            break;
    }
        // Store the current state of the buttons
        previousButtons = currentButtons;
    }
    return 0;
}
